
name: NPM Publish package util-pkg

on:
  push:
    tags:
      - "@reignmodule/util-pkg@*"

jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@v2
      - name: autorize on npm
        working-directory: packages/util-pkg
        env:
          NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
        run: echo "//registry.npmjs.org/:_authToken=$NPM_TOKEN" > .npmrc
      - name: install
        working-directory: packages/util-pkg
        run: npm ci
      - name: publish on npm
        working-directory: packages/util-pkg
        run: npm publish
